// Auto-generated bindings. DO NOT MODIFY.// This file has been generated by Specta. DO NOT EDIT.

import {
    createTauRPCProxy as createProxy,
    type InferCommandOutput,
} from "taurpc";
type TAURI_CHANNEL<T> = (response: T) => void;

const ARGS_MAP = { "": '{"app_version":[]}' };
export type Router = { "": { app_version: () => Promise<string> } };

export type { InferCommandOutput };
export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP);
