[package]
name = "orbital_common"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
strip_bom = "1.0.0"
thiserror = "2.0.12"

[dev-dependencies]
figment = { version = "0.10.19", features = ["toml"] }
